name: Deploy to GitHub Pages

# Controls when the action will run. 
on: 
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2

      - name: wasm pack build
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - run: wasm-pack build --dev --target web --out-name wasm --out-dir static

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: static # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
